---
- name: install openjdk
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: set cassandra repo
  copy: src=cassandra311x.repo dest=/etc/yum.repos.d/cassandra311x.repo owner=root group=root mode=0644

- name: import gpg key
  rpm_key:
    state: present
    key: https://www.apache.org/dist/cassandra/KEYS

- name: update repo cache
  command: yum -q makecache

- name: install cassandra
  yum:
    name: cassandra
    state: present

- name: set cassandra conf
  template: src=cassandra.yaml.j2 dest=/etc/cassandra/conf/cassandra.yaml owner=root group=root mode=0644
  notify: Restart Cassandra

- name: start cassandra
  systemd:
    state: restarted
    daemon_reload: yes
    name: cassandra
    enabled: yes